sudo: false
dist: bionic
language: java

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 10 -L GPL

script: mvn clean install

cache:
  directories:
  - $HOME/.m2